name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: vars
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=commit-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create .env.production
        run: |
          cat <<EOF > .env.production
          VITE_LIFF_ID=${{ secrets.VITE_LIFF_ID }}
          VITE_LIFF_ID_2=${{ secrets.VITE_LIFF_ID_2 }}
          VITE_LIFF_ID_ACHIEVEMENT=${{ secrets.VITE_LIFF_ID_ACHIEVEMENT }}
          BASE_URL=${{ secrets.BASE_URL }}
          VITE_API_URL=${{ secrets.VITE_API_URL }}
          EOF

      - name: Run build script
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          chmod +x ./build.sh
          ./build.sh "$IMAGE_TAG"

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd wpd-project
            docker pull apichayauwu/wpd-liff:${{ steps.vars.outputs.tag }}
            docker-compose up -d --build --pull always
